version: '3.8'
services:
  backend:
    build: .
    container_name: articulos_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: articulos_db
      DB_USER: Flexxus
      DB_PASSWORD: Flexxus
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: articulos_db
      MYSQL_USER: Flexxus
      MYSQL_PASSWORD: Flexxus
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
